// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: app.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Middle_Ping_FullMethodName = "/Middle/Ping"
)

// MiddleClient is the client API for Middle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiddleClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongRes, error)
}

type middleClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddleClient(cc grpc.ClientConnInterface) MiddleClient {
	return &middleClient{cc}
}

func (c *middleClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongRes)
	err := c.cc.Invoke(ctx, Middle_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddleServer is the server API for Middle service.
// All implementations must embed UnimplementedMiddleServer
// for forward compatibility.
type MiddleServer interface {
	Ping(context.Context, *PingReq) (*PongRes, error)
	mustEmbedUnimplementedMiddleServer()
}

// UnimplementedMiddleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiddleServer struct{}

func (UnimplementedMiddleServer) Ping(context.Context, *PingReq) (*PongRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMiddleServer) mustEmbedUnimplementedMiddleServer() {}
func (UnimplementedMiddleServer) testEmbeddedByValue()                {}

// UnsafeMiddleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddleServer will
// result in compilation errors.
type UnsafeMiddleServer interface {
	mustEmbedUnimplementedMiddleServer()
}

func RegisterMiddleServer(s grpc.ServiceRegistrar, srv MiddleServer) {
	// If the following call pancis, it indicates UnimplementedMiddleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Middle_ServiceDesc, srv)
}

func _Middle_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Middle_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Middle_ServiceDesc is the grpc.ServiceDesc for Middle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Middle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Middle",
	HandlerType: (*MiddleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Middle_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
